### ISSUE TITLE
Lost signals

### ISSUE THREAD

**Issue by ddertoni** [mslosarz/nextrtc-signaling-server#16]
I found a problem where some messages (offerRequest most of the time) weren't delivered. The solution we found here is to call `getRemotePeer().flushBatch()` on the method `send()` in class InternalMessage.
Now, it works every time.

**Comment by mslosarz** [comment]
Could you please prepare pull rq for that change - you'll get in avenue of nextRTC stars :D (thank you very much for help, I wasn't able to find this issue for more than half of year :D)
