### ISSUE TITLE
NAT traversal

### ISSUE THREAD

**Issue by dimonik** [mslosarz/nextrtc-signaling-server#2]
Has this server means to traverse NAT: STUN/TURN support?

Will it work over internet or only inside LAN?

**Comment by mslosarz** [comment]
WebRTC supports NAT traversal signaling server provides (pass through) data
required To setup this connection
19 gru 2015 08:30 "dimonik" <notifications@github.com> napisał(a):

**Comment by dimonik** [comment]
I mean, you bundled JavaScript clients here, do they support NAT traversal? Which STUN/TURN servers they are using if so?
