### ISSUE TITLE
Text chat support ?

### ISSUE THREAD

**Issue by olabomba** [mslosarz/nextrtc-signaling-server#21]
Hello again,
I've seen you talked about text chat support in the 6# issue (closed).
I don't see any documentation on this feature, can you provide a short one ?

**Comment by mslosarz** [comment]
Sure I'll but if you have some time try to send signal text with 'to'
parameter set to the other conversation member :)

30 maj 2017 13:31 "olabomba" <notifications@github.com> napisał(a):
