### ISSUE TITLE
org.nextrtc.signalingserver.DaggerNextRTCComponent not found

### ISSUE THREAD

**Issue by leozhaocc** [mslosarz/nextrtc-signaling-server#22]
hi,guys

I can not find the class of org.nextrtc.signalingserver.DaggerNextRTCComponent, how can i get this one?

**Comment by mslosarz** [comment]
Hello

The best way is to build project by maven  (mvn clean install) and later on
refresh yours IDE - This class is autogenerated one.

Best regards

05.08.2017 11:53 "leozhaocc" <notifications@github.com> napisał(a):

**Comment by leozhaocc** [comment]
i understood, thank you very much!
