### ISSUE TITLE
STUN/TURN support?

### ISSUE THREAD

**Issue by ilahsa** [mslosarz/nextrtc-signaling-server#23]
STUN/TURN support? how to do it

**Comment by mslosarz** [comment]
It's client side configuration. You have to pass STUN/TURN addresses during
client setup like in this [example](
https://github.com/mslosarz/nextrtc-example-videochat/blob/master/src/main/webapp/index.html)
(line 55)

16.08.2017 10:58 AM "baibaoqing" <notifications@github.com> napisał(a):
