### ISSUE TITLE
Hope NextRTCEndpoint can extend Endpoint

### ISSUE THREAD

**Issue by hnxuruochen** [mslosarz/nextrtc-signaling-server#24]
https://spring.io/blog/2013/05/23/spring-framework-4-0-m1-websocket-support
In my case the exporter in second method won't use the singleton declared by @bean but create new instance every time when new websocket connected.
So I have to use the third method, registration, but it require that class extends from Endpoint.

**Comment by mslosarz** [comment]
I've tried to get rid of inheritance, but unfortunately with no success. I had problems with missing WebApplicationContext inside SpringConfigurer. Did you manage how to run NextRTC without inheritance?

**Comment by mslosarz** [comment]
Unfortunately I wasn't able to use "standard" way of managing websocket :(. Abstract class provided by me has a lot of tricks to combine spring-context with JSR365. In the future I can think about changing way of creation endpoint (to be in line with spring approach), but It's not my priority
