### ISSUE TITLE
Project build error

### ISSUE THREAD

**Issue by bachden** [mslosarz/nextrtc-signaling-server#25]
I'm trying to checkout source code and import to eclipse, but it show me an error as:
`The import org.nextrtc.signalingserver.DaggerNextRTCComponent cannot be resolved`

![screen shot 2017-09-08 at 10 20 56 am](https://user-images.githubusercontent.com/1224571/30194778-725b2fb0-947f-11e7-9f14-4151950b3a0c.png)
How can I resolve it?

Thank you,

**Comment by mslosarz** [comment]
Run maven clean install and then in target in generated sources you will
find missing class. Mark this directory as sources. (As far as I remember
there was plugin in Eclipse - maven integraton - it should do the job for
you)

08.09.2017 05:21 "bachden" <notifications@github.com> napisał(a):

**Comment by bachden** [comment]
Many thanks
