### ISSUE TITLE
Use modern logging framework

### ISSUE THREAD

**Issue by eugene-rozov** [mslosarz/nextrtc-signaling-server#32]
Log4j 1 had reached end of life. Maybe it is worth to use logging facade like slf4j and allow end user to decide which logging implementation they want.

**Comment by mslosarz** [comment]
I've replaced logging framework. Here is [branch with changes](https://github.com/mslosarz/nextrtc-signaling-server/tree/introduced_slf4j). Could you check in your project whether it is enough? If yes then I'll merge this to master and prepare release

**Comment by eugene-rozov** [comment]
I've tested given branch as a library and it looks good! Could you remove log4j.properties too?

**Comment by mslosarz** [comment]
I've fixed that. New version has been released. Sorry for delays ;) but I had a lot of work to do before the Easter :D
