### ISSUE TITLE
Chat and data channel support

### ISSUE THREAD

**Issue by deepakbandela** [mslosarz/nextrtc-signaling-server#6]
I was successfully able to run your demo on video chat.

Do you have a demo on Chat and data channel as well?

If there is a support how do we make it happen?

**Comment by mslosarz** [comment]
Unfortunately not. I didn't thought to use signaling server as a chatting server, but I think that It's possible to add new signal which will be simple pass between two clients

**Comment by chasd00** [comment]
I was curious about this too, is it as simple as adding MESSAGE to the Signal enum? And then in the JS you'd use nextRTC.request('message',to,data) and nextRTC.on('message', function(nextRTC, event){}); correct?

**Comment by mslosarz** [comment]
In release 0.0.4v I'll add new message called TEXT where you'll be able to send text messages

**Comment by chasd00** [comment]
Great! thank you!

**Comment by mslosarz** [comment]
done in 0.0.4 (I'll add info in documentation how to use it)
