### ISSUE TITLE
Authentication and security

### ISSUE THREAD

**Issue by deepakbandela** [mslosarz/nextrtc-signaling-server#7]
I have an existing web application running in tomcat. I want to use this signalling server integrated with its user system and allow only those who are part of my user system to create rooms. Is there a way to do so? if so how do we make it?

Does this signaling server broad cast the SDP message to all those who are listening(kept open the index.html) to the signaling server? 

In other words I want to know the aspects of security if we are going to use this.

**Comment by mslosarz** [comment]
There is nextrtc-videochat-with-rest. In this project I'll show how to integrate nextrtc with existing application. 

You can simply authenticate user by spring-security. The simplest way is to add path protection. (Only authenticated users have access to url where si exposed signaling endpoint)

In current implementation SPD is propagated to all of users in conversation.
