### ISSUE TITLE
Doesn't support more than two users

### ISSUE THREAD

**Issue by kishorejaladich** [mslosarz/nextrtc-signaling-server#8]
Hi, i saw your project its awesome.But i see it doesn't support more than two users at once, the second user is replaced with the third user when he joins new and if third with fourth, that happens so on. What can i do to have more than two users displayed?

**Comment by mslosarz** [comment]
Hello

Example provided by me is only for 2 person. If you want to connect more
peoples you have to modify example (for example by adding new video tag
when new person appears). In example (index.html) you can see that there're
only two tags with video (with id local and remote)

Best regards

2016-03-14 9:47 GMT+01:00 kishorejaladich <notifications@github.com>:

> Hi, i saw your project its awesome.But i see it doesn't support more than
> two users at once, the second user is replaced with the third user when he
> joins new and if third with fourth, that happens so on. What can i do to
> have more than two users displayed?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mslosarz/nextrtc-signaling-server/issues/8>.
>



-- 
Marcin Ślósarz
